# Generated by Django 4.2.7 on 2025-07-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
    ]
